build_script:
  - cmd: dotnet restore
  - cmd: cd XPathParserTest
  - cmd: dotnet test
  - cmd: cd ..\XPathParser
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

on_success:
  - ps: Push-AppveyorArtifact "bin\Release\XPathParser.*.nupkg"